name: Go Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Show Go env (debug)
        run: go env

      - name: Download Go modules
        run: go mod download

      - name: Install golangci-lint from source
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run -v --timeout 10m --max-issues-per-linter 0 --max-same-issues 0
